### ISSUE TITLE
Breaks mob spawners despite function beeing disabled

### ISSUE THREAD

**Issue by odkupiciel375** [Globox1997/AdditionZ#1]
Despite max_spawner_count being set to 0, which according to its description supposed to disable this function it still breaks them. It seems like its breaking them when the game tries to spawn another wave - spawned 1 group of two mobs and destroyed itself after a short little while.
![image](https://user-images.githubusercontent.com/19805800/196518157-cca7cfba-678f-4e9b-a7a5-417d3cbafd25.png)

**Comment by Fortist** [comment]
Seconding this

**Comment by Globox1997** [comment]
Thanks for report, fixed with [https://github.com/Globox1997/AdditionZ/commit/dd68e862f94d5e3ccc9bbf4294689e88dd34a539](https://github.com/Globox1997/AdditionZ/commit/dd68e862f94d5e3ccc9bbf4294689e88dd34a539)
