### ISSUE TITLE
[Bug] Stampede Enchantment goes on pickaxe & co.

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/AdditionZ#10]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.22

### Mod Version

newest

### Describe the Issue

Stampede Enchantment is apply able on pickaxes.

Shouldnt it be only for shields? (Im not sure)

### latest.log

no log

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdditionZ/commit/a312c0f443a8f0e63877566ba9f7aa5cd908dd52](https://github.com/Globox1997/AdditionZ/commit/a312c0f443a8f0e63877566ba9f7aa5cd908dd52)
