### ISSUE TITLE
iron golem glitch

### ISSUE THREAD

**Issue by peow** [Globox1997/AdditionZ#11]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric v0.14.22

### Mod Version

1.1.10

### Describe the Issue

I'm using AdditionZ in a modpack I created, however I noticed that the Iron Golem is hitting me from a long distance, much greater than normal, and this stops happening when I remove AdditionZ from the modpack
![image](https://github.com/Globox1997/AdditionZ/assets/105888751/9bfe7b62-2d34-4b54-b34d-248cd894262a)

i tried to disable all options inside AdditionZ with Mod Menu, but nothing changed, the bug only stop when i delete the mod
![image](https://github.com/Globox1997/AdditionZ/assets/105888751/a28632f0-0413-470d-aeaf-9bc4a85e0710)

### latest.log

no log

### Do you use any other mods except the required ones?

yes

**Comment by VoltWolf** [comment]
Minecraft 1.20.1
Fabric v0.14.24
AdditionZ 1.1.10
Can confirm. Iron golem able to hit me even when standing on a 3 block pillar and at a very long range when chasing me. Tested in both singleplayer and multiplayer using a Fabric server with AdditionZ installed client side and server side.

**Comment by Globox1997** [comment]
Sounds like a feature

**Comment by peow** [comment]
what?

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdditionZ/commit/9ed08008ee764b15bcacb0b620981fe8ea05a7d7](https://github.com/Globox1997/AdditionZ/commit/9ed08008ee764b15bcacb0b620981fe8ea05a7d7)

**Comment by peow** [comment]
tx for fixing, i noticed that the iron golem can reach you even if you are on a pillar of 4 blocks, in vanilla Minecraft it can only reach up to 2 blocks high

![2023-11-03_14 52 08](https://github.com/Globox1997/AdditionZ/assets/105888751/a8185539-eef3-4438-a947-3f297b40fd6f)


i dont think this is completely bad, I would prefer it to only reach 3 blocks in height, but 4 I think is a bit too much

i would appreciate it if you could make an update to Fabric Loader 0.14.22 and Fabric API 0.90.7 as my modpack is in that version ;(
