### ISSUE TITLE
Can´t turn off Creepers burning during daylight.

### ISSUE THREAD

**Issue by Dragonoyyd** [Globox1997/AdditionZ#15]
### Minecraft Version

1.19.x

### Mod Loader Version

Fabric

### Mod Version

1.1.10

### Describe the Issue

Turned "creeper_on_fire": false but they are still burning during daylight. How do i turn this off ? 

### latest.log

[latest.log](https://github.com/Globox1997/AdditionZ/files/13769239/latest.log)

**Comment by Globox1997** [comment]
AdditionZ does not change how daylight affects creepers. This setting you were talking about is creeper would explode when they are on fire [https://github.com/Globox1997/AdditionZ/blob/1.20/src/main/java/net/additionz/mixin/CreeperEntityMixin.java](https://github.com/Globox1997/AdditionZ/blob/1.20/src/main/java/net/additionz/mixin/CreeperEntityMixin.java)
