### ISSUE TITLE
[Bug]: Jukebox Error - Failed to load data

### ISSUE THREAD

**Issue by xR4YM0ND** [Globox1997/AdditionZ#16]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.3

### Mod Version

1.2.0

### Describe the Issue

If the jukebox feature is true (i guess)

![image](https://github.com/Globox1997/AdditionZ/assets/97298005/f42b7894-8ec8-462a-af58-8f2c666cab89)

### latest.log

https://discord.com/channels/745451299713056791/1191376188929736764

### Do you use any other mods except the required ones?

yeeeeees

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdditionZ/commit/b0521c92b3a8a04cf5e0de9cd069a95730f24338](https://github.com/Globox1997/AdditionZ/commit/b0521c92b3a8a04cf5e0de9cd069a95730f24338)
