### ISSUE TITLE
[BUG] Dexterity Enchantment is launching you up in the air

### ISSUE THREAD

**Issue by DeadRote** [Globox1997/AdditionZ#19]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.3

### Mod Version

1.2.2

### Describe the Issue

**Description:**
 With Dexterity Enchantment on the boots (any boots), if you walk backwards to the ladder, while looking straight down/up (90 degree angle) - you will be launched into the air

**To Reproduce:**
1. Look Down/Up with your camera
2. Stand backwards to the Ladder
3. Move to the ladder with holding S
4. Release S when you touched the Ladder

![ezgif-2-d8508f690f](https://github.com/Globox1997/AdditionZ/assets/5835836/6a5ced52-9474-453e-b134-8b40bac6e05a)

**Potential Cause:**
Conflict/Multiplication between 2 Injections of the same applyClimbingSpeed (first for Shift release, second for the Enchantment itself) 

**Tested both standalone single-player, standalone server, and with other mods**

### latest.log

No logs

### Do you use any other mods except the required ones?

-

**Comment by Globox1997** [comment]
Dang xD

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdditionZ/commit/d0870cbe289df62471e1a4a6539896d50627e1b2](https://github.com/Globox1997/AdditionZ/commit/d0870cbe289df62471e1a4a6539896d50627e1b2)
