### ISSUE TITLE
NBT Crafting does not use Addition slot except for potions

### ISSUE THREAD

**Issue by RW-Blackbird** [Globox1997/AdditionZ#2]
This appears to be present both in custom datapack NBT recipes, and in the mod itself with the spectral arrows. When trying to craft a spectral arrow in the fletching table, it only produces 6 normal arrows. The same issue happens when I try to add custom recipes, though tipped arrows work, and custom recipes that use the top, middle, and bottom slot seem to work as well.

**Comment by Globox1997** [comment]
This is odd, thanks for reporting, fixed with [https://github.com/Globox1997/AdditionZ/commit/de41446d5a20b30838b87678edacfa3dcacdd156](https://github.com/Globox1997/AdditionZ/commit/de41446d5a20b30838b87678edacfa3dcacdd156)
