### ISSUE TITLE
additionz fletching table GUI does not stay open with variants fletching table 3rd party mod

### ISSUE THREAD

**Issue by DadoIrie** [Globox1997/AdditionZ#20]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.6

### Mod Version

1.2.3

### Describe the Issue

fletching table gui from additionz does not stay open with the variant fletching table (standalone fletching table variants (https://www.curseforge.com/minecraft/mc-mods/variant-fletching-tables) as well vanilla blocks fletching table variants(https://www.curseforge.com/minecraft/mc-mods/variant-vanilla-blocks)) as shown on discord with the uploaded clip record

### latest.log

log doesn't really tell anything what's happening - anyways here you go: https://mclo.gs/jntUAgl

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/AdditionZ/commit/181ca006cbc325b510544acf6ba828ce9e33be95](https://github.com/Globox1997/AdditionZ/commit/181ca006cbc325b510544acf6ba828ce9e33be95)
