### ISSUE TITLE
Trinkets feature needs to be removed

### ISSUE THREAD

**Issue by emilyploszaj** [Globox1997/AdditionZ#21]
### Minecraft Version

1.20.x

### Mod Loader Version

N/A

### Mod Version

N/A

### Describe the Issue

The Trinkets "feature" added in <https://github.com/Globox1997/AdditionZ/commit/e7b14dfae40892df6d737561cb4c4a392032d078> is causing issues for Trinkets users and needs to be removed.
Users are coming into my discord guild with issues like this and I have no way to solve them.
![image](https://github.com/Globox1997/AdditionZ/assets/14813658/8f9936cc-79cb-47ac-88d0-abe403770189)

A feature like this would be welcome in a Trinkets feature PR, behind a config flag, assuming it is implemented properly.

If this feature must exist outside of Trinkets, which I do not recommend, it needs to be put it in its own proper mod that has both a name and a description describing its relationship to Trinkets. It is not acceptable to have random third party mods with no clear relationship with Trinkets causing issues with the mod and frustrating users.

### latest.log

N/A

**Comment by peow** [comment]
Wouldn't it help if this feature was disabled by default?
perhaps having a warning when the person tries to enable it, saying that this feature may contain bugs and that errors should not be reported to Trinkets but to AdditionZ?

**Comment by Globox1997** [comment]
Seems like there is indeed a bug with the slot positions (tested only with less than 9 trinket slots), was so sure it would work xD.

However as @peow suggested, I would rather turn this feature off by default (cause all features in this mod are toggleable).
Fixed the position bug and turned off the feature by default with [https://github.com/Globox1997/AdditionZ/commit/cb3a044dc154b14423a3e76c0341460b634e1c1e](https://github.com/Globox1997/AdditionZ/commit/cb3a044dc154b14423a3e76c0341460b634e1c1e).

Imo such a small feature does not deserve its own mod and it is basically the idea for the Addition mod to collect just small features (yes other mods of mine are small feature mods but I try to decrease them).
 Not sure how you take on PRs so I just added it to this mod. Thanks for the info tho.

I hope that is okay for you and your discord does not get more users asking for help or just report this bug.
If not, let me know. Publised the changes with v1.3.1

**Comment by Globox1997** [comment]
Any thoughts @emilyploszaj ?

**Comment by emilyploszaj** [comment]
It is preferable to have this off by default and that eases some of the problem but I still believe something this drastic should be part of trinkets or in a mod that is clearly for this purpose.

**Comment by Globox1997** [comment]
Okay, than I'll keep it off by default, thx for the reply.
