### ISSUE TITLE
Incompatibility with Amendments

### ISSUE THREAD

**Issue by lxly9** [Globox1997/AdditionZ#23]
### Minecraft Version

1.20.x

### Mod Loader Version

Quilt Loader 0.25.0-beta.2 (happens on other versions as well)

### Mod Version

1.3.1

### Describe the Issue

When using [Amendments](https://modrinth.com/mod/amendments) with AdditionZ the game crashes on startup (it has to do with the jukebox mixin). even when jukebox modifications are disabled in both mods it stillc rashes on startup.

### latest.log

[crash-2024-04-10_13.13.23.4409-quilt_loader.txt](https://github.com/Globox1997/AdditionZ/files/14931394/crash-2024-04-10_13.13.23.4409-quilt_loader.txt)

**Comment by Globox1997** [comment]
Seems like this is fixed on 1.21.
Out of time reasons I only work on the latest version of my mods.
