### ISSUE TITLE
Pathblock speeding not turning off.

### ISSUE THREAD

**Issue by Cailex05** [Globox1997/AdditionZ#3]
this one is a big issue, it still happens even if i uninstall the mod so yeah it's pretty cursed.
even if i set it to 0 there's still the speed effect

**Comment by Globox1997** [comment]
Mh this sounds not good but should never happen.

**Comment by Globox1997** [comment]
The path speed boost can not be removed if the boost settings is set to 0.
If this bug you mentioned still persist with the latest version, reopen this issue.
