### ISSUE TITLE
REI support (1.19.2)

### ISSUE THREAD

**Issue by DadoIrie** [Globox1997/AdditionZ#5]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Was about to edit some recipes from other mods which do add arrows, but then saw that the recipe isn't shown in REI nor is the recipe type being registered by KubeJS despite using the minecraft namespace (`minecraft:fletching`) - which confused me a bit, but somebody helped me out with it and discovered that AdditionZ itself registered that new recipe type. not a big thingy - just confusing for people which do look the recipe files
KubeJS isn't either a big thingy - could be useful tho - but the REI support would be quite essential and therefore would ask if AdditionsZ could add REI support so that recipes actually show up in there?

**Comment by Globox1997** [comment]
Added the recipe type on emi.

**Comment by Globox1997** [comment]
Added with [https://github.com/Globox1997/AdditionZ/commit/1764e319380ca2d43a8d0268315891106ee6e144](https://github.com/Globox1997/AdditionZ/commit/1764e319380ca2d43a8d0268315891106ee6e144) to the latest version.
Out of time reasons I only work on the latest versions of my mods.
