### ISSUE TITLE
AdditionZ & WTHIT server crash

### ISSUE THREAD

**Issue by DadoIrie** [Globox1997/AdditionZ#6]
### Minecraft Version

1.19.x

### Mod Loader Version

0.14.21

### Mod Version

1.1.10

### Describe the Issue

When loading AdditionZ with WTHIT on a server the server crashes with `java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'wthit'` & `Caused by: java.lang.RuntimeException: Cannot load class net.additionz.AdditionClient in environment type SERVER`

### latest.log

https://mclo.gs/gEjbWhx

**Comment by Globox1997** [comment]
This should fix the issue [https://github.com/Globox1997/AdditionZ/commit/77c51b3784dc3151b36e08e9476adb61b67db80a](https://github.com/Globox1997/AdditionZ/commit/77c51b3784dc3151b36e08e9476adb61b67db80a)
