### ISSUE TITLE
EMI Compatibility for Fletching Table recipes

### ISSUE THREAD

**Issue by Ultimushadow** [Globox1997/AdditionZ#7]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Using EMI and AdditionZ I noticed that there wasn't a group for fletching table recipes, now I _think_ I can add them myself with a datapack but it would be much easier if they had internal support!

**Comment by Globox1997** [comment]
Added support on the latest version ;)
