### ISSUE TITLE
Stampede config for input key

### ISSUE THREAD

**Issue by Ultimushadow** [Globox1997/AdditionZ#8]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

Hey there, I love the stampede enchantment but I find hitting the sprint button a little cumbersome in combat like that (I use the default sprint key). Personally, I was hoping you would add an option to change it to the attack key, at least in my brain I perceive it more as an attack then movement, and you can't attack with a shield up anyways. It might be beneficial to just add it's own keybind to whatever you want it to be though, so others can pick if they want a different key for it. Let me know what you think!

**Comment by Globox1997** [comment]
I hardcoded it intentionally since if you use a shield in real life you can push whatever is in your way by sprinting forward.
You could code an addon to make it a separate key binding but currently I have no plans to do so.
